### ISSUE TITLE
[FR] - Change the button text per TV basis

### ISSUE THREAD

**Issue by rtripault** [Bruno17/multiItemsGridTV#12]
It would be cool to be able to customize the text displayed on the button (add item) on a TV basis.
Ex.: i use one MIGX TV to add images, so i'd like the text button to be "add an image". In another MIGX TV i use it to add locations,  so the text button should be "add a new location".

Hope i'm understandable :)

Cheers

**Comment by Bruno17** [comment]
added a field to input-properties
