### ISSUE TITLE
Images currently don't work in Revo 2.1.0-rc4

### ISSUE THREAD

**Issue by adamwintle** [Bruno17/multiItemsGridTV#14]
I'm not sure if you're already aware of this issue but at the moment in MODX Revolution 2.1.0-rc4 images don't display on the front-end of the site; yet adding them in the back-end Manager works fine.

My code looks like this:

MIGX TV code:

**Form Tabs:**

`````` [
{"caption":"Info", "fields": [
    {"field":"title","caption":"Title"},
    {"field":"image","caption":"Image","inputTV":"work-gallery-image"}
]}
] ```

**Grid Columns:**
```[
{"header": "Title", "width": "160", "sortable": "true", "dataIndex": "title"}, 
{"header": "Image", "width": "50", "sortable": "false", "dataIndex": "image","renderer": "this.renderImage"}
]```

With "work-gallery-image" being a standard image TV with output of "default".

Then the Template output is:

```[[!getImageList? &tvname=`work-gallery` &tpl=`work.gallery.image`]]```

And the ```work.gallery.image``` chunk:

```<a href="[[+image]]" rel="slideshow" class="image[[+idx]]">
  <span class="magnify-button-small"></span>
  <img src="[[+image]]" title="[[+title]]" width="560" /></a>​```

Let me know if you need any more specific info...
``````

**Comment by Bruno17** [comment]
what is your output with that? (copied from firebug)

**Comment by adamwintle** [comment]
The output looks like this:

http://screenshots.adamwintle.com/MIGX-error.jpg

The `<img>` tag contained within the `<a id="project-video">` tag is working which isn't part of the MIGX call; then the lower `<a id="work-additional-videos">` is the MIGX template where infinite extra videos can be added to the page. The titles and captions are loading, but the `<img>` tags SRC is coming up blank...

**Comment by adamwintle** [comment]
This is the HTML output:

http://screenshots.adamwintle.com/migx-error2.jpg

Notice the SRC for the video is also not working, which is a standard File TV input with Default output.

**Comment by Bruno17** [comment]
what is the output just with [[*work-gallery]]?

please paste your code here, not a  link to a screeshot!

**Comment by adamwintle** [comment]
oops sorry about those screenshots.

This is the output of [[*work-gallery]]

`[{"title":"DOP Sarah Bartles-Smith and Assistamt Camera Alison Lai","image":"assets/images/galleries/five/five01.jpg"},{"title":"Actors Deborah Ann Gaetano and Jude Samuel","image":"assets/images/galleries/five/2944373536_199c236b43_o.jpg"},{"title":"VFX Supervisor Chris Sayer and DOP Sarah Bartles-Smith","image":"assets/images/galleries/five/2943511337_03fa749bc6_o.jpg"},{"title":"VFX Supervisor Chris Sayer and Producer Natalie Busuttil","image":"assets/images/galleries/five/2943511765_cac9e4c8a3_o.jpg"}]`

**Comment by Bruno17** [comment]
hmm.. this looks good so far. Didn't test it in rc4 yet. 
And you are sure with [[+image]] you get an empty output?

Are normal image-TVs (not in MIGX) with the same images and with default-output-type working?

**Comment by adamwintle** [comment]
Yeah I'm sure the [[+image]] placeholders are showing up empty; and there are other normal image-TVs elsewhere on the page which are working fine.

I upgraded from RC3 to RC4 and at that point MIGX stopped working; this site isn't live yet, so you're welcome to login to the Manager and have a look around if you think it'll help? - email me directly or add me on Google Talk (me@adamwintle.com) and I'll set you up a login.

**Comment by Bruno17** [comment]
I've no issues on rc4, all is working as it was on rc3 for me

**Comment by adamwintle** [comment]
I got this working - For anyone wondering, the issue was being caused by having the image-TVs [[+work-gallery-image]] added to the Resource's template - in RC3 I had added them but hidden them using the Form Customiser; in RC4 it broke the output.
