### ISSUE TITLE
Richtext TV in another context

### ISSUE THREAD

**Issue by rtripault** [Bruno17/multiItemsGridTV#17]
It might not be related to MIGX since other TV type work as intended, but while using a richtext TV with MIGX in a context other than web, the input isn't saved.

**Comment by rtripault** [comment]
After some tests, the "input value not saved" occurs in Safari (Windows)

In Firefox 4, Firebug give those errors:
`uncaught exception: TypeError: event.originalTarget.getElementsByTagName is not a function`

`uncaught exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMNSHTMLDocument.execCommand]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: *url*/assets/components/tinymce/jscripts/tiny_mce/tiny_mce.js?v=211pl :: <TOP_LEVEL> :: line 1"  data: no]`

In IE9, the text area isn't "focusable" by clicking on it (you have to use the tab key), but the data is recorded

**Comment by okyanet** [comment]
Hi Romaine, was a solution to this ever found? 

I can reproduce the issue in Chrome (Mac) but it appears to work ok in Firefox.

When editing a RichText TV input type using TinyMCE, the input is not recorded. It's lost when closing the window, before saving the resource.
