### ISSUE TITLE
Enable SaveButton when removing items

### ISSUE THREAD

**Issue by oleics** [Bruno17/multiItemsGridTV#20]
I cant save if i remove items from the grid.

**Comment by eprochasson** [comment]
+1

Modification to elements with MIGX (reordering, adding, updating...) does not re-enable the Save button. Using Ctrl+S works, but is not really user friendly.

(since I'm here, thanks for MIGX: that's a very nice and useful piece of code)

**Comment by Bruno17** [comment]
this is fixed now
