### ISSUE TITLE
Passing variables into getImageList tpl

### ISSUE THREAD

**Issue by rponudic** [Bruno17/multiItemsGridTV#24]
It would be great if I could pass variables to the template used in getImageList tpl:

**Snippet call**
[[getImageList &tpl=`my-custom-tpl` &imageWidth=`200` ]]

**Chunk: my-custom-tpl**
&lt;img src="[[+image]]" width="[[+imageWidth]]" /&gt;

**Comment by Bruno17** [comment]
there are several ways to get there.

for example you can create a TV with name imageWidth and use it like that:
`<img src="[[+image]]" width="[[*imageWidth]]" />`

but when I think about it, its possible to merge the scriptproperties to the fields array

**Comment by rponudic** [comment]
That would be really great! 

As you said you always have to create TVs for such things. If the template has a lot of configuration you end up with quite a messed up TV configuration - I would prefer to do it this way - I think it's much cleaner - don't you?

**Comment by rponudic** [comment]
Do you plan to implement this feature? If not, I'll try to do it and submit a pull request to you...

**Comment by Bruno17** [comment]
added this feature to the latest commit
