### ISSUE TITLE
Multiple MIGX TVs not possible?

### ISSUE THREAD

**Issue by RITF** [Bruno17/multiItemsGridTV#25]
I created a nice MIGX tv and it worked great.

I then created a second one and the new migx tv is just not working: 

I enter data and not only does it not show up in the grid columns but I can't even close the MIGX editor window unless I hit 'cancel' (though it adds an empty row to the grid).

It doesn't seem to be a browser issue, as its the same in safari & firefox.

I've tried everything I could think of - i.e. I made duplicate tvs instead of using common tvs across the two instances of migx..

Was it wrong to assume I can have more than one MIGX tv? Or is there something else going on?

**Comment by RITF** [comment]
OK - - for whomever might be having this problem, I seem to have solved it by renaming everything inside the migx input options. So, not just avoiding common input TVs as noted above but also choosing different names for the headers, captions, and fields.

I'm not closing the issue & will instead wait in case the author has some insight into what - barring some typo disaster on my end - might have been happening here.

BTW, thank you Bruno17 for an amazing modx extra and thanks in advance for any input here.

**Comment by Bruno17** [comment]
Just tested with two exact same MIGX-TVs (same grid-columns and same form-tabs). 
Could not reproduce your issues. 
This did work without problems.

**Comment by RITF** [comment]
Thanks for the (quite timely) response - - but just for the record, the problem had occurred trying to use some but not all of the same input TVs between two different MIGX-TVs. Of course it is possible I f*$cked something else up, of course...
