### ISSUE TITLE
Input-Options disappear on quick editing a MIGX-tv

### ISSUE THREAD

**Issue by thomasd** [Bruno17/multiItemsGridTV#26]
First of, thank you Bruno for this great add-on to MODx.

When quick editing (right click on the elements-tree) a MIGX-tv (and saving), say to change the category, the input-options disappear. The data is still there but the scheme is gone.
I have installed the newest version of MODx, 2.1.3 and the newest version of MIGX, 1.1.0rc2.
Can somebody confirm this, or is it only a problem on my installation.

**Comment by Bruno17** [comment]
I'm not sure, but may be its a general problem with all TVs, not only with MIGX-TV.
Can someone confirm this?

I remember, had the same issue when duplicating a MIGX-TV or when changing the input-type and change it back.

**Comment by thomasd** [comment]
I can confirm, it is a general problem in MODx. Tested it with a simple input-type of "text", setting the min-length. After doing a quick-edit, the input-options disappeared. I will submit a bug-report.
