### ISSUE TITLE
When you delete a table row, the save button does not become enabled

### ISSUE THREAD

**Issue by sonicpunk** [Bruno17/multiItemsGridTV#30]
Hi Bruno,

Just as the title says, when I delete a row in the manager, because the save button is not active, I then need to place the cursor in some other field in the Manager in order to activate it and save the change.

Kind regards,
Ben

**Comment by Bruno17** [comment]
Hi Ben,
see this commit: https://github.com/Bruno17/multiItemsGridTV/commit/59f5f662ce84908ab0343cf434e89263eb370141

**Comment by sonicpunk** [comment]
Thanks Bruno!
