### ISSUE TITLE
No migx package in Package Manager Revo 2.2rc(1-2)

### ISSUE THREAD

**Issue by vasia123** [Bruno17/multiItemsGridTV#32]
I have not found migx package via search or manually, it is incompatible with version 2.2?

**Comment by Bruno17** [comment]
MIGX for Revo 2.2 isn't ready for the repo.
But you can use it from here (the master-branch)

**Comment by avanturist888** [comment]
Ok, thanks for the answer.

**Comment by adamj88** [comment]
How do you install it once you upload the files from the archive?

**Comment by avanturist888** [comment]
I uploaded files from https://github.com/Bruno17/multiItemsGridTV/tree/master/core/packages to the folder /core/packages , and then install. Please read this instruction: http://rtfm.modx.com/display/revolution20/Package+Management#PackageManagement-DownloadingPackages

**Comment by Bruno17** [comment]
there isn't a package with the latest changes. just copy all extracted files (assets/components/migx and core/components/migx) to your server.
