### ISSUE TITLE
Front End Limit

### ISSUE THREAD

**Issue by adamj88** [Bruno17/multiItemsGridTV#34]
Hi,

I've got 18 different items in the back end, on the front it will only pull in 16 for some reason. If I duplicate one in the back end it just replaces one of the others on the front end, but I always end up with 16.

On getImageList I've tried &limit not set (so should default to 0?) and I've tried setting it to 300, but no matter what I always get 16 on the front.

Any ideas why this is?

Thanks

**Comment by ghost** [comment]
Looks like I have a similar issue with one of my sites as well. Looking at the JSON code, I see the same MIGX ID twice:
"MIGX_id": "10",

and where it should be 21, it also reads:
"MIGX_id": "10"

Looks like something goes wrong while adding the records. Maybe a JS issue?

**Comment by Bruno17** [comment]
should be fixed now also for the old MIGX-version for revo before 2.2 here on github
https://github.com/Bruno17/multiItemsGridTV/commit/7c3607ef2ba7171567aeb9041b6b85dcdf991726

**Comment by ghost** [comment]
Thanks! This fixed it for me.
