### ISSUE TITLE
Installation not so straightforward as described

### ISSUE THREAD

**Issue by gerritvanaaken** [Bruno17/multiItemsGridTV#7]
All necessary files are there (in the current state of the repository), but when installing the add-on, you have to manually copy some files in different locations like "multiitemsgrid.tpl" or "multiitemsgrid.php". Maybe you can update the wiki page with the outdated installing instructions!

**Comment by Bruno17** [comment]
no need to move files. Just install the plugin! I will upgrade the wiki once all is working in 2.1

**Comment by rtripault** [comment]
As Bruno said, just copy over the file (don't forget to delete the old ones if you were using a previous version).
Then create a plugin, name it whatever you'd like (let's say multiitems), copy/paste the content of the file located in https://github.com/Bruno17/multiItemsGridTV/blob/master/core/components/multiitemsgridTv/elements/plugins/multiitemsgridTv.plugin.php into your newly created plugin, on the « system events » tab, tick OnTVInputRenderList, OnTVOutputRenderList and OnTVOutputRenderPropertiesList.

You now should be done (exept the property set part, explained in the wiki). I hope this will help :)

Edit: sorry i forgot, create a namespace : Name > multiitemsgridTv; Path > {core_path}components/multiitemsgridTv/

**Comment by gerritvanaaken** [comment]
That’s what I meant – with the current instructions, you have no chance to find out how to setup the add-on. I understand, however, that this is work in progress. And it works quite well!

**Comment by Bruno17** [comment]
the namespace should be created automatically - didn_t it?

**Comment by rtripault** [comment]
@Bruno17: might be, but since i was having troubles (because of the "old" files) i created it manually. I'll try to delete it

Edit: everything works flawlessly without manually creating the namespace
